In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reversed_arr=np.flip(arr)
print(reversed_arr)

[6 5 4 3 2 1]


In [4]:
import numpy as np
arr=np.array([[1,2,3],[2,3,4],[3,4,5]])
flat_arr=arr.flatten()
print(flat_arr)

[1 2 3 2 3 4 3 4 5]


In [7]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[1,3],[3,5]])
print(a==b)

[[ True False]
 [ True False]]


In [11]:
import numpy as np
arr=np.array([1,2,1,2,3,4,3,2,4,21,2,3,12,2,2,4])
most_freq = np.bincount(arr).argmax()
print("the most repeated value is ",most_freq)
indices = np.where(arr == most_freq)
print(" and their indices are ", indices)

the most repeated value is  2
 and their indices are  (array([ 1,  3,  7, 10, 13, 14]),)


In [12]:
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')
print("sum of matrix" , gfg.sum())
print("row wise sum" , gfg.sum(axis=1))
print("coloumn wise sum" , gfg.sum(axis=0))

sum of matrix 45
row wise sum [[14]
 [16]
 [15]]
coloumn wise sum [[20  9 16]]


In [13]:
import numpy as np
n_array=np.array([[55, 25, 15],[30, 44, 2],[11, 45, 77]])
diag_sum = np.trace(n_array)
print("diagnol sum of matrix is " , diag_sum)
eigenvalue , eigenvector = np.linalg.eig(n_array)
print("eigen value of matrix is " , eigenvalue)
print("eigenvector of matrix is " , eigenvector)
inverse = np.linalg.inv(n_array)
print("inverse of matrix is " , inverse)
det = np.linalg.det(n_array)
print("determinant of matrix is " , det)

diagnol sum of matrix is  176
eigen value of matrix is  [98.16835147 28.097044   49.73460452]
eigenvector of matrix is  [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
inverse of matrix is  [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
determinant of matrix is  137180.0000000001


In [15]:
import numpy as np
p = [[1, 2], [2, 3]] 
q = [[4, 5], [6, 7]] 
arr = np.dot(p,q)
print(arr)
cov_matrix = np.cov(p,q)
print("covarience is " , cov_matrix)


[[16 19]
 [26 31]]
covarience is  [[0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]]


In [16]:
import numpy as np
p = [[1, 2], [2, 3], [4,5]] 
q = [[4, 5 , 1], [6, 7 , 2]] 
arr = np.dot(p,q)
print(arr)
cov_matrix = np.cov(p,q)
print("covarience is " , cov_matrix)

[[16 19  5]
 [26 31  8]
 [46 55 14]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [17]:
import numpy as np

x = np.array([[2, 3, 4],[3, 2, 9]])
y = np.array([[1, 5, 0],[5, 10, 3]])

inner = np.inner(x, y)
print("Inner product:\n", inner)
outer = np.outer(x, y)
print("Outer product:\n", outer)



Inner product:
 [[17 52]
 [13 62]]
Outer product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]


In [19]:
import numpy as np

array = np.array([[1, -2, 3],
                  [-4, 5, -6]])

abs_array = np.abs(array)
print("i. Absolute values:\n", abs_array)

print("\nii. Percentiles:")

print("Flattened:", np.percentile(array, [25, 50, 75]))


print("Column-wise:\n", np.percentile(array, [25, 50, 75], axis=0))


print("Row-wise:\n", np.percentile(array, [25, 50, 75], axis=1))


print("\niii. Statistics:")


print("Flattened → Mean:", np.mean(array), 
      "Median:", np.median(array), 
      "Std Dev:", np.std(array))


print("Column-wise → Mean:", np.mean(array, axis=0))
print("Column-wise → Median:", np.median(array, axis=0))
print("Column-wise → Std Dev:", np.std(array, axis=0))

print("Row-wise → Mean:", np.mean(array, axis=1))
print("Row-wise → Median:", np.median(array, axis=1))
print("Row-wise → Std Dev:", np.std(array, axis=1))


i. Absolute values:
 [[1 2 3]
 [4 5 6]]

ii. Percentiles:
Flattened: [-3.5 -0.5  2.5]
Column-wise:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]

iii. Statistics:
Flattened → Mean: -0.5 Median: -0.5 Std Dev: 3.8622100754188224
Column-wise → Mean: [-1.5  1.5 -1.5]
Column-wise → Median: [-1.5  1.5 -1.5]
Column-wise → Std Dev: [2.5 3.5 4.5]
Row-wise → Mean: [ 0.66666667 -1.66666667]
Row-wise → Median: [ 1. -4.]
Row-wise → Std Dev: [2.05480467 4.78423336]
